# Key metadata about the site
site_name: Albert Health Clinical Safety Management File
site_description: Albert Health Clinical Safety Management File
site_author: Albert Health
site_url:

# MkDocs processes files in this folder into a HTML site
docs_dir: clinical-safety-management-file

# Copyright information which is shown in the footer
copyright: Copyright &copy; 2022 Albert Health

# These lines configure the 'GitHub repo' widget on the top right
repo_url: https://github.com/bawmedical/albert-health-dcb0129-csmf
repo_name: bawmedical/albert-health-dcb0129-csmf
edit_uri: blob/main/clinical-safety-management-file

# For local development `mkdocs serve` serves the docs locally on this port
dev_addr: "127.0.0.1:8001"

# Navigation structure


# Theme settings, fonts, colours
theme:
  name: material
  features:
    - navigation.instant
    # uncomment the below two lines for Tabbed navigation (along the header bar)
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.expand
    # - toc.integrate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    code: Roboto Mono

# MkDocs plugins
plugins:
  - git-committers:
      repository: bawmedical/albert-health-dcb0129-csmf
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - with-pdf:
      #cover: false
      #back_cover: true
      #cover_title: TITLE TEXT
      #cover_subtitle: SUBTITLE TEXT
      #custom_template_path: TEMPLATES PATH
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #render_js: true
      #headless_chrome_path: headless-chromium
      output_path: pdf/albert-health-clinical-safety-management-file.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #debug_html: true
      #show_anchors: true
      #verbose: true

# Additional markdown features
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true

# Set extra CSS file
extra_css:
  - _assets/_stylesheets/extra.css

extra:
  site_slug: albert-health-clinical-safety-management-file
# Uncomment to add social icons
# social:
#   - icon: fontawesome/brands/twitter
#     link: https://twitter.com/exampleorgstwitter
#   - icon: fontawesome/brands/github
#     link: https://github.com/exampleorgsgithub
